//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class ClearScenarioMsg : Message
    {
        public const string k_RosMessageName = "video_logging/ClearScenario";
        public override string RosMessageName => k_RosMessageName;

        public bool camera;
        public bool point_cloud;
        public bool infologs;
        public bool tf;

        public ClearScenarioMsg()
        {
            this.camera = false;
            this.point_cloud = false;
            this.infologs = false;
            this.tf = false;
        }

        public ClearScenarioMsg(bool camera, bool point_cloud, bool infologs, bool tf)
        {
            this.camera = camera;
            this.point_cloud = point_cloud;
            this.infologs = infologs;
            this.tf = tf;
        }

        public static ClearScenarioMsg Deserialize(MessageDeserializer deserializer) => new ClearScenarioMsg(deserializer);

        private ClearScenarioMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.camera);
            deserializer.Read(out this.point_cloud);
            deserializer.Read(out this.infologs);
            deserializer.Read(out this.tf);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.camera);
            serializer.Write(this.point_cloud);
            serializer.Write(this.infologs);
            serializer.Write(this.tf);
        }

        public override string ToString()
        {
            return "ClearScenarioMsg: " +
            "\ncamera: " + camera.ToString() +
            "\npoint_cloud: " + point_cloud.ToString() +
            "\ninfologs: " + infologs.ToString() +
            "\ntf: " + tf.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
